_target_: lambo5utr.optimizers.lambo.LaMBO
_recursive_: False
num_rounds: 64
num_gens: 16
num_opt_steps: 32
patience: 32
lr: 0.1
concentrate_pool: 1
mutation_method: one_per_seq # mask_annealing for DNABERT
annealing_epochs: 16
mask_ratio: 0.125
resampling_weight: 1.
encoder_obj: mlm 
optimize_latent: True
position_sampler: uniform
entropy_penalty: 1e-2
window_size: 1
latent_init: null
replacement_method: normal # normal, mask_dominant, kmer_mask
ref_point_method: nadir
