_target_: lambo5utr.models.lm_elements.LanguageModel
name: mlm_cnn

model:
  _target_: lambo5utr.models.shared_elements.mCNN
  tokenizer: ${tokenizer}
  max_seq_len: ${task.max_seq_len}
  embed_dim: 64
  latent_dim: 16
  out_dim: 16
  kernel_size: 5
  p: 0.
  layernorm: True
  max_len_delta: 0

batch_size: 32
num_epochs: 128
patience: 32
max_shift: 0
mask_ratio: 0.125
device: ${device}
device_id: ${device_id}